language: android

jdk:
  - oraclejdk8

android:
    components:
        - platform-tools
        - tools
        - android-23
        - build-tools-23.0.3
        - extra-android-m2repository
        - extra-android-support
        - extra-google-admob_ads_sdk 
        - extra-google-m2repository

git:
  depth: 1

script: TERM=dumb ./gradlew --stacktrace clean check

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
