language: android

jdk:
  - oraclejdk8

android:
    components:
        - platform-tools
        - tools
        - android-24
        - build-tools-24.0.0
        - extra-android-m2repository
        - extra-google-m2repository

git:
  depth: 1

script: TERM=dumb ./gradlew --stacktrace clean check -x :bvandroidsdktesting:lint

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
