language: android

jdk: oraclejdk7

android:
    components:
        - platform-tools
        - tools
        - android-23
        - build-tools-23.0.2
        - extra-android-m2repository
        - extra-android-support
        - extra-google-admob_ads_sdk 
        - extra-google-m2repository

cache:
  directories:
    - $HOME/.gradle

script: TERM=dumb ./gradlew --stacktrace build

sudo: false

