language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-28"

git:
  depth: 1

script:
  - if ["$TRAVIS_BRANCH" == "master"]; then TERM=dumb ./gradlew --stacktrace clean check;
    else TERM=dumb ./gradlew --stacktrace checkstyle lintDebug findbugs testDebugUnitTest --parallel;
    fi

branches:
  except:
    - gh-pages

sudo: true

cache:
  directories:
    - $HOME/.gradle